# Generated by Django 5.0.6 on 2024-06-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_book_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="is_published",
            field=models.BooleanField(
                choices=[(0, "Черновик"), (1, "Опубликовано")], default=1
            ),
        ),
    ]
