# Generated by Django 5.0.6 on 2024-06-15 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_genre_alter_book_rating_book_genre_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="genre_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="books.genre"
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="genre",
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
