# Generated by Django 5.0.6 on 2024-06-15 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0007_rename_genre_id_book_genre"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="genre",
            new_name="genre_id",
        ),
    ]
