# Generated by Django 5.0.6 on 2024-06-15 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0008_rename_genre_book_genre_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="genre_id",
            new_name="genre",
        ),
    ]
