# Generated by Django 5.0.6 on 2024-06-15 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0010_tagbooks_alter_book_genre_book_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="tags",
        ),
        migrations.DeleteModel(
            name="TagBooks",
        ),
    ]
