# Generated by Django 5.0.6 on 2024-06-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0011_remove_book_tags_delete_tagbooks"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(db_index=True, max_length=100)),
                ("slug", models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tags", to="books.tags"
            ),
        ),
    ]
