# Generated by Django 5.0.6 on 2024-06-16 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0013_author_book_aboba"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
    ]
