# Generated by Django 5.0.6 on 2024-06-16 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0014_remove_book_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="aboba",
            new_name="author",
        ),
    ]
