# Generated by Django 5.0.6 on 2024-06-18 16:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0016_alter_book_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads_model")),
            ],
        ),
        migrations.AlterModelOptions(
            name="author",
            options={"verbose_name": "Автор", "verbose_name_plural": "Авторы"},
        ),
        migrations.AlterModelOptions(
            name="book",
            options={
                "ordering": ["id", "-rating", "-title"],
                "verbose_name": "Книга",
                "verbose_name_plural": "Книги",
            },
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={"verbose_name": "Жанр", "verbose_name_plural": "Жанры"},
        ),
        migrations.AlterModelOptions(
            name="tags",
            options={"verbose_name": "Тэг", "verbose_name_plural": "Тэги"},
        ),
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="author",
            name="surname",
            field=models.CharField(max_length=255, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="author",
                to="books.author",
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="books",
                to="books.genre",
                verbose_name="Жанр",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="is_published",
            field=models.BooleanField(verbose_name="Опубликовано"),
        ),
        migrations.AlterField(
            model_name="book",
            name="rating",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(5),
                    django.core.validators.MinValueValidator(0),
                ],
                verbose_name="Рейтинг",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tags", to="books.tags", verbose_name="Тэги"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="time_create",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Время создания"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="time_update",
            field=models.DateTimeField(auto_now=True, verbose_name="Время обновления"),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=70, verbose_name="Заголовок"),
        ),
        migrations.AlterField(
            model_name="genre",
            name="genre",
            field=models.CharField(db_index=True, max_length=50, verbose_name="Жанр"),
        ),
        migrations.AlterField(
            model_name="tags",
            name="tag",
            field=models.CharField(db_index=True, max_length=100, verbose_name="Тэг"),
        ),
    ]
