# Generated by Django 5.0.6 on 2024-06-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0017_uploadfile_alter_author_options_alter_book_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="photo",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="photos/%Y/%m/%d",
                verbose_name="Обложка книги",
            ),
        ),
        migrations.AlterField(
            model_name="uploadfile",
            name="file",
            field=models.ImageField(upload_to="uploads_model"),
        ),
    ]
